manifest:
  version: 0.9
  remotes:
    - name: sit
      url-base: https://github.com/svhoy/uwb_zephyr_project
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: dw3000
      url-base: https://github.com/br101/

  defaults:
    remote: sit

  projects:
    - name: zephyr
      repo-path: zephyr
      remote: zephyrproject
      revision: v3.2-branch
      import:
        name-whitelist:
          - cmsis
          - edtt
          - fatfs
          - hal_nordic
          - libmetal
          - littlefs
          - lvgl
          - mbedtls
          - mcumgr
          - mipi-sys-t
          - net-tools
          - nrf_hw_models
          - openthread
          - segger
          - tinycrypt
    - name: dw3000-decadriver
      repo-path: zephyr-dw3000-decadriver
      remote: dw3000
      revision: master



  self:
    path: sit
